# BlueSageDLP Database Users and Secrets

# All of the following assumes the BlueSageDLP architecture using the T2 infrastructure model.

# Terms:

# BSDLP_ENVIRONMENT: dev, test, prod
# BSDLP_CLIENT: client1
# BSDLP_TIER: lower, prod

# Proposal:

# Use AWS Parameter Store as the gold source for DB credentials. 

# Design:

# Simple as possible design for effective RBAC. Secrets will be organized as follows:

# /systems/system-name/tier-name/parameter-name
# /clients/environment-name/parameter-name

# aws ssm put-parameter --name "/systems/flyway/lower/dlp_fly" --value "your_value" --type "SecureString"

# aws ssm put-parameter --name "/clients/dev/client1_dev" --value "your_value" --type "SecureString"

# System Credentials

# Currently, the master database user and password are stored in AWS Secrets Manager using the naming convention: bluedlp-${BSDLP_TIER}-db.

# e.g., bluedlp-lower-db

# In that secret, we find a user named: bluedlp_${BSDLP_TIER}_admin

# e.g., bluedlp_lower_admin

- script: create-users
  sources:
    test-connection:
      data: >
        SELECT 1;
    create-schema:
      data: >
        CREATE DATABASE <BSDLP_CLIENT>_<BSDLP_ENVIRONMENT> CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    drop-schema:
      data: >
        DROP DATABASE <BSDLP_CLIENT>_<BSDLP_ENVIRONMENT>;
    mysql-config:
      data: |+
        [client]
        user = "<REPLACE_USER>"
        password = "<REPLACE_PASSWORD>"
        host = "<REPLACE_HOST>"
  setup:
    - description: check suthentication status
      command: sts
      sub-command: get-caller-identity
    - description: get the database credentials
      command: secretsmanager
      sensitive: true
      sub-command: get-secret-value
      arguments:
        - name: secret-id
          value: bluedlp-lower-db
    - description: parse the secret string
      executable: jq
      sub-command: -r
      command: .SecretString
      sensitive: true
      source: create-users:setup:step-1
    - description: parse the host
      executable: jq
      sub-command: -r
      command: .host
      source: create-users:setup:step-2
    - description: parse the username
      executable: jq
      sub-command: -r
      command: .username
      source: create-users:setup:step-2
    - description: parse the port
      executable: jq
      sub-command: -r
      command: .port
      source: create-users:setup:step-2
    - description: parse the password
      executable: jq
      sensitive: true
      sub-command: -r
      command: .password
      source: create-users:setup:step-2
    - description: build mysql config file
      executable: cat
      sensitive: true
      source: mysql-config
      replacements:
        - match: <REPLACE_USER>
          replace-with: create-users:setup:step-4
        - match: <REPLACE_PASSWORD>
          replace-with: create-users:setup:step-6
        - match: <REPLACE_HOST>
          replace-with: create-users:setup:step-3
    - description: test connection
      executable: mysql
      source: test-connection
      arguments:
        - name: use-config
          style: plain
          value: --defaults-extra-file=/tmp/_mysql-config.json
    - description: stash secret in ssm parameter
      command: ssm
      sensitive: true
      sub-command: put-parameter
      arguments:
        - name: name
          value: "/systems/mysql/lower/defaults-extra-file"
        - name: type
          value: "SecureString"
        - name: overwrite
        - name: value
          source: create-users:setup:step-7
          source-type: text
  main:
    - description: create schema
      executable: mysql
      source: create-schema
      replacements:
        - match: <BSDLP_CLIENT>
          replace-with: __CLIENT__
        - match: <BSDLP_ENVIRONMENT>
          replace-with: __ENVIRONMENT__
      arguments:
        - name: use-config
          style: plain
          value: --defaults-extra-file=/tmp/_mysql-config.json
  cleanup:
    - description: delete parameter
      command: ssm
      sub-command: delete-parameter
      arguments:
        - name: name
          value: "/systems/mysql/lower/defaults-extra-file"
    - description: drop schema
      executable: mysql
      source: drop-schema
      replacements:
        - match: <BSDLP_CLIENT>
          replace-with: __CLIENT__
        - match: <BSDLP_ENVIRONMENT>
          replace-with: __ENVIRONMENT__
      arguments:
        - name: use-config
          style: plain
          value: --defaults-extra-file=/tmp/_mysql-config.json

